// prototype HTM.c
// Generated by decompiling D:\How-To-Mine\prototype HTM.exe
// using Decompiler version 0.5.5.0.

#include "prototype HTM.h"

void fn0000000000401180()
{
fn0000000000401180_entry:
l0000000000401180:
	dwLoc04 = rbp
	dwLoc08 = fp - 0x08
	dwLoc0C = rbp
	dwLoc10 = rdi
	dwLoc14 = rsi
	dwLoc18 = rbx
	rsp = fp - 0xB0
	eax = 0x00
	SZO = cond(0x00)
	C = false
	ecx = 0x0D
	rdx = fp - 0x90
	rdi = fp - 0x90
	goto l000000000040119E
l0000000000401180:
	dwLoc04 = rbp
	dwLoc08 = fp - 0x08
	dwLoc0C = rbp
	dwLoc10 = rdi
	dwLoc14 = rsi
	dwLoc18 = rbx
	rsp = fp - 0xB0
	eax = 0x00
	SZO = cond(0x00)
	C = false
	ecx = 0x0D
	rdx = fp - 0x90
	rdi = fp - 0x90
	goto l000000000040119E
l0000000000401180:
	rsp = fp - 0x04
	dwLoc04 = rbp
	rsp = fp - 0x08
	dwLoc08 = fp - 0x08
	rsp = fp - 0x0C
	dwLoc0C = rbp
	rsp = fp - 0x10
	dwLoc10 = rdi
	rsp = fp - 0x14
	dwLoc14 = rsi
	rsp = fp - 0x18
	dwLoc18 = rbx
	rsp = fp - 0xB0
	eax = 0x00
	SZO = cond(0x00)
	C = false
	ecx = 0x0D
	rdx = fp - 0x90
	rdi = fp - 0x90
	goto l000000000040119E
l000000000040119E:
	branch rcx == 0x00 l00000000004011A1
	goto l000000000040119E_1
l000000000040119E:
	branch rcx == 0x00 l00000000004011A1
	goto l000000000040119E_1
l000000000040119E:
	branch rcx == 0x00 l00000000004011A1
	goto l000000000040119E_1
l000000000040119E_1:
	Mem0[rdi + 0x00:word64] = rax
	rdi = rdi + 0x08
	rcx = rcx - 0x01
	goto l000000000040119E
l000000000040119E_1:
	Mem0[rdi + 0x00:word64] = rax
	rdi = rdi + 0x08
	rcx = rcx - 0x01
	goto l000000000040119E
l000000000040119E_1:
	Mem0[rdi + 0x00:word64] = rax
	rdi = rdi + 0x08
	rcx = rcx - 0x01
	goto l000000000040119E
l00000000004011A1:
	rdi = Mem0[0x00000000004063E0 + 0x00:word64]
	r9d = Mem0[r15 + 0x00:word32]
	SZO = cond(r9d & r9d)
	C = false
	branch Test(NE,Z) l0000000000401470
	goto l00000000004011B4
l00000000004011A1:
	rdi = Mem0[0x00000000004063E0 + 0x00:word64]
	r9d = Mem0[r15 + 0x00:word32]
	SZO = cond(r9d & r9d)
	C = false
	branch Test(NE,Z) l0000000000401470
	goto l00000000004011B4
l00000000004011A1:
	rdi = Mem0[0x00000000004063E0 + 0x00:word64]
	r9d = Mem0[r15 + 0x00:word32]
	SZO = cond(r9d & r9d)
	C = false
	branch Test(NE,Z) l0000000000401470
	goto l00000000004011B4
l00000000004011B4:
	rax = Mem0[gs:0x30:word64]
	rbx = Mem0[0x0000000000406330 + 0x00:word64]
	ebp = 0x00
	SZO = cond(0x00)
	C = false
	rsi = Mem0[rax + 0x08:word64]
	r12 = Mem0[0x000000000040A27C + 0x00:word64]
	goto l00000000004011E4
l00000000004011B4:
	rax = Mem0[gs:0x30:word64]
	rbx = Mem0[0x0000000000406330 + 0x00:word64]
	ebp = 0x00
	SZO = cond(0x00)
	C = false
	rsi = Mem0[rax + 0x08:word64]
	r12 = Mem0[0x000000000040A27C + 0x00:word64]
	goto l00000000004011E4
l00000000004011B4:
	rax = Mem0[gs:0x30:word64]
	rbx = Mem0[0x0000000000406330 + 0x00:word64]
	ebp = 0x00
	SZO = cond(0x00)
	C = false
	rsi = Mem0[rax + 0x08:word64]
	r12 = Mem0[0x000000000040A27C + 0x00:word64]
	goto l00000000004011E4
l00000000004011D3:
	SCZO = cond(rsi - rax)
	branch Test(EQ,Z) l0000000000401410
	goto l00000000004011DC
l00000000004011D3:
	SCZO = cond(rsi - rax)
	branch Test(EQ,Z) l0000000000401410
	goto l00000000004011DC
l00000000004011D3:
	SCZO = cond(rsi - rax)
	branch Test(EQ,Z) l0000000000401410
	goto l00000000004011DC
l00000000004011DC:
	ecx = 1000
	call r12d (retsize: 4; depth: 4)
	goto l00000000004011E4
l00000000004011DC:
	ecx = 1000
	call r12d (retsize: 4; depth: 4)
	goto l00000000004011E4
l00000000004011DC:
	ecx = 1000
	call r12d (retsize: 4; depth: 4)
	goto l00000000004011E4
l00000000004011E4:
	rax = rbp
	__lock()
	Z = __cmpxchg(Mem0[rbx + 0x00:word64], rsi, Mem0, out Mem0)
	SZO = cond(rax & rax)
	C = false
	branch Test(NE,Z) l00000000004011D3
	goto l00000000004011F1
l00000000004011E4:
	rax = rbp
	__lock()
	Z = __cmpxchg(Mem0[rbx + 0x00:word64], rsi, Mem0, out Mem0)
	SZO = cond(rax & rax)
	C = false
	branch Test(NE,Z) l00000000004011D3
	goto l00000000004011F1
l00000000004011E4:
	rax = rbp
	__lock()
	Z = __cmpxchg(Mem0[rbx + 0x00:word64], rsi, Mem0, out Mem0)
	SZO = cond(rax & rax)
	C = false
	branch Test(NE,Z) l00000000004011D3
	goto l00000000004011F1
l00000000004011F1:
	rsi = Mem0[0x0000000000406340 + 0x00:word64]
	ebp = 0x00
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(EQ,Z) l0000000000401427
	goto l0000000000401205
l00000000004011F1:
	rsi = Mem0[0x0000000000406340 + 0x00:word64]
	ebp = 0x00
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(EQ,Z) l0000000000401427
	goto l0000000000401205
l00000000004011F1:
	rsi = Mem0[0x0000000000406340 + 0x00:word64]
	ebp = 0x00
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(EQ,Z) l0000000000401427
	goto l0000000000401205
l0000000000401205:
	eax = Mem0[rsi + 0x00:word32]
	SZO = cond(eax & eax)
	C = false
	branch Test(EQ,Z) l0000000000401480
	goto l000000000040120F
l0000000000401205:
	eax = Mem0[rsi + 0x00:word32]
	SZO = cond(eax & eax)
	C = false
	branch Test(EQ,Z) l0000000000401480
	goto l000000000040120F
l0000000000401205:
	eax = Mem0[rsi + 0x00:word32]
	SZO = cond(eax & eax)
	C = false
	branch Test(EQ,Z) l0000000000401480
	goto l000000000040120F
l000000000040120F:
	Mem0[0x0000000000409004 + 0x00:word32] = 0x01
	goto l0000000000401219
l000000000040120F:
	Mem0[0x0000000000409004 + 0x00:word32] = 0x01
	goto l0000000000401219
l000000000040120F:
	Mem0[0x0000000000409004 + 0x00:word32] = 0x01
	goto l0000000000401219
l0000000000401219:
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(EQ,Z) l000000000040143C
	goto l0000000000401224
l0000000000401219:
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(EQ,Z) l000000000040143C
	goto l0000000000401224
l0000000000401219:
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(EQ,Z) l000000000040143C
	goto l0000000000401224
l0000000000401224:
	SZO = cond(ebp & ebp)
	C = false
	branch Test(EQ,Z) l000000000040145D
	goto l000000000040122C
l0000000000401224:
	SZO = cond(ebp & ebp)
	C = false
	branch Test(EQ,Z) l000000000040145D
	goto l000000000040122C
l0000000000401224:
	SZO = cond(ebp & ebp)
	C = false
	branch Test(EQ,Z) l000000000040145D
	goto l000000000040122C
l000000000040122C:
	rax = Mem0[0x00000000004062D0 + 0x00:word64]
	rax = Mem0[rax + 0x00:word64]
	SZO = cond(rax & rax)
	C = false
	branch Test(EQ,Z) l0000000000401247
	goto l000000000040123B
l000000000040122C:
	rax = Mem0[0x00000000004062D0 + 0x00:word64]
	rax = Mem0[rax + 0x00:word64]
	SZO = cond(rax & rax)
	C = false
	branch Test(EQ,Z) l0000000000401247
	goto l000000000040123B
l000000000040122C:
	rax = Mem0[0x00000000004062D0 + 0x00:word64]
	rax = Mem0[rax + 0x00:word64]
	SZO = cond(rax & rax)
	C = false
	branch Test(EQ,Z) l0000000000401247
	goto l000000000040123B
l000000000040123B:
	r8d = 0x00
	edx = 0x02
	ecx = 0x00
	SZO = cond(0x00)
	C = false
	call eax (retsize: 4; depth: 4)
	goto l0000000000401247
l000000000040123B:
	r8d = 0x00
	edx = 0x02
	ecx = 0x00
	SZO = cond(0x00)
	C = false
	call eax (retsize: 4; depth: 4)
	goto l0000000000401247
l000000000040123B:
	r8d = 0x00
	edx = 0x02
	ecx = 0x00
	SZO = cond(0x00)
	C = false
	call eax (retsize: 4; depth: 4)
	goto l0000000000401247
l0000000000401247:
	call fn0000000000402590 (retsize: 8; depth: 8)
	rcx = 0x0000000000402AE0
	eax = SetUnhandledExceptionFilter(Mem0[rsp + 0x00:LPTOP_LEVEL_EXCEPTION_FILTER])
	rsp = rsp + 0x08
	rdx = Mem0[0x0000000000406320 + 0x00:word64]
	Mem0[rdx + 0x00:word64] = rax
	call fn00000000004029F0 (retsize: 8; depth: 8)
	rcx = 0x0000000000401000
	call fn0000000000403460 (retsize: 8; depth: 8)
	call fn0000000000402390 (retsize: 8; depth: 8)
	rax = Mem0[0x00000000004062E0 + 0x00:word64]
	Mem0[0x0000000000409968 + 0x00:word64] = rax
	call fn0000000000403470 (retsize: 8; depth: 8)
	ecx = 0x00
	rax = Mem0[rax + 0x00:word64]
	SZO = cond(rax & rax)
	C = false
	branch Test(NE,Z) l00000000004012B2
	goto l0000000000401296
l0000000000401247:
	call fn0000000000402590 (retsize: 8; depth: 8)
	rcx = 0x0000000000402AE0
	eax = SetUnhandledExceptionFilter(Mem0[rsp + 0x00:LPTOP_LEVEL_EXCEPTION_FILTER])
	rsp = rsp + 0x08
	rdx = Mem0[0x0000000000406320 + 0x00:word64]
	Mem0[rdx + 0x00:word64] = rax
	call fn00000000004029F0 (retsize: 8; depth: 8)
	rcx = 0x0000000000401000
	call fn0000000000403460 (retsize: 8; depth: 8)
	call fn0000000000402390 (retsize: 8; depth: 8)
	rax = Mem0[0x00000000004062E0 + 0x00:word64]
	Mem0[0x0000000000409968 + 0x00:word64] = rax
	call fn0000000000403470 (retsize: 8; depth: 8)
	ecx = 0x00
	rax = Mem0[rax + 0x00:word64]
	SZO = cond(rax & rax)
	C = false
	branch Test(NE,Z) l00000000004012B2
	goto l0000000000401296
l0000000000401247:
	call fn0000000000402590 (retsize: 8; depth: 8)
	rcx = 0x0000000000402AE0
	eax = SetUnhandledExceptionFilter(Mem0[rsp + 0x00:LPTOP_LEVEL_EXCEPTION_FILTER])
	rsp = rsp + 0x08
	rdx = Mem0[0x0000000000406320 + 0x00:word64]
	Mem0[rdx + 0x00:word64] = rax
	call fn00000000004029F0 (retsize: 8; depth: 8)
	rcx = 0x0000000000401000
	call fn0000000000403460 (retsize: 8; depth: 8)
	call fn0000000000402390 (retsize: 8; depth: 8)
	rax = Mem0[0x00000000004062E0 + 0x00:word64]
	Mem0[0x0000000000409968 + 0x00:word64] = rax
	call fn0000000000403470 (retsize: 8; depth: 8)
	ecx = 0x00
	rax = Mem0[rax + 0x00:word64]
	SZO = cond(rax & rax)
	C = false
	branch Test(NE,Z) l00000000004012B2
	goto l0000000000401296
l0000000000401296:
	goto l00000000004012F7
l0000000000401296:
	goto l00000000004012F7
l0000000000401296:
	goto l00000000004012F7
l00000000004012A0:
	SZO = cond(dl & dl)
	C = false
	branch Test(EQ,Z) l00000000004012D0
	goto l00000000004012A4
l00000000004012A0:
	SZO = cond(dl & dl)
	C = false
	branch Test(EQ,Z) l00000000004012D0
	goto l00000000004012A4
l00000000004012A0:
	SZO = cond(dl & dl)
	C = false
	branch Test(EQ,Z) l00000000004012D0
	goto l00000000004012A4
l00000000004012A4:
	ecx = ecx & 0x01
	SZO = cond(ecx)
	C = false
	branch Test(EQ,Z) l00000000004012D0
	goto l00000000004012A9
l00000000004012A4:
	ecx = ecx & 0x01
	SZO = cond(ecx)
	C = false
	branch Test(EQ,Z) l00000000004012D0
	goto l00000000004012A9
l00000000004012A4:
	ecx = ecx & 0x01
	SZO = cond(ecx)
	C = false
	branch Test(EQ,Z) l00000000004012D0
	goto l00000000004012A9
l00000000004012A9:
	ecx = 0x01
	goto l00000000004012AE
l00000000004012A9:
	ecx = 0x01
	goto l00000000004012AE
l00000000004012A9:
	ecx = 0x01
	goto l00000000004012AE
l00000000004012AE:
	rax = rax + 0x01
	SCZO = cond(rax)
	goto l00000000004012B2
l00000000004012AE:
	rax = rax + 0x01
	SCZO = cond(rax)
	goto l00000000004012B2
l00000000004012AE:
	rax = rax + 0x01
	SCZO = cond(rax)
	goto l00000000004012B2
l00000000004012B2:
	edx = (word32) Mem0[rax + 0x00:byte]
	SCZO = cond(dl - 0x20)
	branch Test(LE,SZO) l00000000004012A0
	goto l00000000004012BA
l00000000004012B2:
	edx = (word32) Mem0[rax + 0x00:byte]
	SCZO = cond(dl - 0x20)
	branch Test(LE,SZO) l00000000004012A0
	goto l00000000004012BA
l00000000004012B2:
	edx = (word32) Mem0[rax + 0x00:byte]
	SCZO = cond(dl - 0x20)
	branch Test(LE,SZO) l00000000004012A0
	goto l00000000004012BA
l00000000004012BA:
	r8d = ecx
	r8d = r8d ^ 0x01
	SCZO = cond(dl - 0x22)
	branch Test(NE,Z) l00000000004012C8
	goto l00000000004012C4_1
l00000000004012BA:
	r8d = ecx
	r8d = r8d ^ 0x01
	SCZO = cond(dl - 0x22)
	branch Test(NE,Z) l00000000004012C8
	goto l00000000004012C4_1
l00000000004012BA:
	r8d = ecx
	r8d = r8d ^ 0x01
	SCZO = cond(dl - 0x22)
	branch Test(NE,Z) l00000000004012C8
	goto l00000000004012C4_1
l00000000004012C4_1:
	ecx = r8d
	goto l00000000004012C8
l00000000004012C4_1:
	ecx = r8d
	goto l00000000004012C8
l00000000004012C4_1:
	ecx = r8d
	goto l00000000004012C8
l00000000004012C8:
	goto l00000000004012AE
l00000000004012C8:
	goto l00000000004012AE
l00000000004012C8:
	goto l00000000004012AE
l00000000004012D0:
	SZO = cond(dl & dl)
	C = false
	branch Test(NE,Z) l00000000004012E5
	goto l00000000004012D4
l00000000004012D0:
	SZO = cond(dl & dl)
	C = false
	branch Test(NE,Z) l00000000004012E5
	goto l00000000004012D4
l00000000004012D0:
	SZO = cond(dl & dl)
	C = false
	branch Test(NE,Z) l00000000004012E5
	goto l00000000004012D4
l00000000004012D4:
	goto l00000000004012F0
l00000000004012D4:
	goto l00000000004012F0
l00000000004012D4:
	goto l00000000004012F0
l00000000004012E0:
	SCZO = cond(dl - 0x20)
	branch Test(GT,SZO) l00000000004012F0
	goto l00000000004012E5
l00000000004012E0:
	SCZO = cond(dl - 0x20)
	branch Test(GT,SZO) l00000000004012F0
	goto l00000000004012E5
l00000000004012E0:
	SCZO = cond(dl - 0x20)
	branch Test(GT,SZO) l00000000004012F0
	goto l00000000004012E5
l00000000004012E5:
	rax = rax + 0x01
	edx = (word32) Mem0[rax + 0x00:byte]
	SZO = cond(dl & dl)
	branch Test(NE,Z) l00000000004012E0
	rax = rax + 0x01
	edx = (word32) Mem0[rax + 0x00:byte]
	SZO = cond(dl & dl)
	C = false
	branch Test(NE,Z) l00000000004012E0
	goto l00000000004012F0
l00000000004012E5:
	rax = rax + 0x01
	edx = (word32) Mem0[rax + 0x00:byte]
	SZO = cond(dl & dl)
	branch Test(NE,Z) l00000000004012E0
	rax = rax + 0x01
	edx = (word32) Mem0[rax + 0x00:byte]
	SZO = cond(dl & dl)
	C = false
	branch Test(NE,Z) l00000000004012E0
	goto l00000000004012F0
l00000000004012E5:
	rax = rax + 0x01
	edx = (word32) Mem0[rax + 0x00:byte]
	SZO = cond(dl & dl)
	branch Test(NE,Z) l00000000004012E0
	rax = rax + 0x01
	edx = (word32) Mem0[rax + 0x00:byte]
	SZO = cond(dl & dl)
	C = false
	branch Test(NE,Z) l00000000004012E0
	goto l00000000004012F0
l00000000004012F0:
	Mem0[0x0000000000409960 + 0x00:word64] = rax
	Mem0[0x0000000000409960 + 0x00:word64] = rax
	Mem0[0x0000000000409960 + 0x00:word64] = rax
	goto l00000000004012F7
l00000000004012F0:
	Mem0[0x0000000000409960 + 0x00:word64] = rax
	Mem0[0x0000000000409960 + 0x00:word64] = rax
	Mem0[0x0000000000409960 + 0x00:word64] = rax
	goto l00000000004012F7
l00000000004012F0:
	Mem0[0x0000000000409960 + 0x00:word64] = rax
	Mem0[0x0000000000409960 + 0x00:word64] = rax
	Mem0[0x0000000000409960 + 0x00:word64] = rax
	goto l00000000004012F7
l00000000004012F7:
	r8d = Mem0[r15 + 0x00:word32]
	SZO = cond(r8d & r8d)
	C = false
	branch Test(EQ,Z) l0000000000401315
	goto l00000000004012FF
l00000000004012F7:
	r8d = Mem0[r15 + 0x00:word32]
	SZO = cond(r8d & r8d)
	C = false
	branch Test(EQ,Z) l0000000000401315
	goto l00000000004012FF
l00000000004012F7:
	r8d = Mem0[r15 + 0x00:word32]
	SZO = cond(r8d & r8d)
	C = false
	branch Test(EQ,Z) l0000000000401315
	goto l00000000004012FF
l00000000004012FF:
	SZO = cond(Mem0[rsp + 0x5C:byte] & 0x01)
	C = false
	eax = 0x0A
	branch Test(NE,Z) l0000000000401400
	goto l000000000040130F
l00000000004012FF:
	SZO = cond(Mem0[rsp + 0x5C:byte] & 0x01)
	C = false
	eax = 0x0A
	branch Test(NE,Z) l0000000000401400
	goto l000000000040130F
l00000000004012FF:
	SZO = cond(Mem0[rsp + 0x5C:byte] & 0x01)
	C = false
	eax = 0x0A
	branch Test(NE,Z) l0000000000401400
	goto l000000000040130F
l000000000040130F:
	Mem0[0x0000000000404000 + 0x00:word32] = eax
	goto l0000000000401315
l000000000040130F:
	Mem0[0x0000000000404000 + 0x00:word32] = eax
	goto l0000000000401315
l000000000040130F:
	Mem0[0x0000000000404000 + 0x00:word32] = eax
	goto l0000000000401315
l0000000000401315:
	ebx = Mem0[0x0000000000409020 + 0x00:word32]
	r12d = r11 + 0x01
	r12 = (int64) r12d
	r12 = r12 << 0x03
	rcx = r12
	eax = malloc(Mem0[rsp + 0x00:size_t])
	SZO = cond(ebx & ebx)
	C = false
	rdi = Mem0[0x0000000000409018 + 0x00:word64]
	rbp = rax
	branch Test(LE,SZO) l0000000000401387
	goto l000000000040133C
l0000000000401315:
	ebx = Mem0[0x0000000000409020 + 0x00:word32]
	r12d = r11 + 0x01
	r12 = (int64) r12d
	r12 = r12 << 0x03
	rcx = r12
	eax = malloc(Mem0[rsp + 0x00:size_t])
	SZO = cond(ebx & ebx)
	C = false
	rdi = Mem0[0x0000000000409018 + 0x00:word64]
	rbp = rax
	branch Test(LE,SZO) l0000000000401387
	goto l000000000040133C
l0000000000401315:
	ebx = Mem0[0x0000000000409020 + 0x00:word32]
	r12d = r11 + 0x01
	r12 = (int64) r12d
	r12 = r12 << 0x03
	rcx = r12
	eax = malloc(Mem0[rsp + 0x00:size_t])
	SZO = cond(ebx & ebx)
	C = false
	rdi = Mem0[0x0000000000409018 + 0x00:word64]
	rbp = rax
	branch Test(LE,SZO) l0000000000401387
	goto l000000000040133C
l000000000040133C:
	eax = rbx - 0x01
	ebx = 0x00
	SZO = cond(0x00)
	C = false
	r13 = 0x08 + rax * 0x08
	goto l0000000000401350
l000000000040133C:
	eax = rbx - 0x01
	ebx = 0x00
	SZO = cond(0x00)
	C = false
	r13 = 0x08 + rax * 0x08
	goto l0000000000401350
l000000000040133C:
	eax = rbx - 0x01
	ebx = 0x00
	SZO = cond(0x00)
	C = false
	r13 = 0x08 + rax * 0x08
	goto l0000000000401350
l0000000000401350:
	rcx = Mem0[rdi + rbx:word64]
	eax = strlen(Mem0[rsp + 0x00:(ptr char)])
	rsi = rax + 0x01
	eax = malloc(Mem0[rsp + 0x00:size_t])
	r8 = rsi
	Mem0[rbp + 0x00 + rbx:word64] = rax
	rdx = Mem0[rdi + rbx:word64]
	rcx = rax
	rbx = rbx + 0x08
	eax = memcpy(Mem0[rsp + 0x00:(ptr void)], Mem0[rsp + 0x08:(ptr void)], Mem0[rsp + 0x0010:size_t])
	SCZO = cond(r13 - rbx)
	branch Test(NE,Z) l0000000000401350
	goto l0000000000401382
l0000000000401350:
	rcx = Mem0[rdi + rbx:word64]
	eax = strlen(Mem0[rsp + 0x00:(ptr char)])
	rsi = rax + 0x01
	eax = malloc(Mem0[rsp + 0x00:size_t])
	r8 = rsi
	Mem0[rbp + 0x00 + rbx:word64] = rax
	rdx = Mem0[rdi + rbx:word64]
	rcx = rax
	rbx = rbx + 0x08
	eax = memcpy(Mem0[rsp + 0x00:(ptr void)], Mem0[rsp + 0x08:(ptr void)], Mem0[rsp + 0x0010:size_t])
	SCZO = cond(r13 - rbx)
	branch Test(NE,Z) l0000000000401350
	goto l0000000000401382
l0000000000401350:
	rcx = Mem0[rdi + rbx:word64]
	eax = strlen(Mem0[rsp + 0x00:(ptr char)])
	rsi = rax + 0x01
	eax = malloc(Mem0[rsp + 0x00:size_t])
	r8 = rsi
	Mem0[rbp + 0x00 + rbx:word64] = rax
	rdx = Mem0[rdi + rbx:word64]
	rcx = rax
	rbx = rbx + 0x08
	eax = memcpy(Mem0[rsp + 0x00:(ptr void)], Mem0[rsp + 0x08:(ptr void)], Mem0[rsp + 0x0010:size_t])
	SCZO = cond(r13 - rbx)
	branch Test(NE,Z) l0000000000401350
	goto l0000000000401382
l0000000000401382:
	rax = rbp - 0x08
	goto l0000000000401387
l0000000000401382:
	rax = rbp - 0x08
	goto l0000000000401387
l0000000000401382:
	rax = rbp - 0x08
	goto l0000000000401387
l0000000000401387:
	Mem0[rax + 0x00:word64] = 0x00
	Mem0[0x0000000000409018 + 0x00:word64] = rbp
	call fn0000000000401F50 (retsize: 8;)
	rax = Mem0[0x00000000004062F0 + 0x00:word64]
	rdx = Mem0[0x0000000000409010 + 0x00:word64]
	ecx = Mem0[0x0000000000409020 + 0x00:word32]
	rax = Mem0[rax + 0x00:word64]
	Mem0[rax + 0x00:word64] = rdx
	r8 = Mem0[0x0000000000409010 + 0x00:word64]
	rdx = Mem0[0x0000000000409018 + 0x00:word64]
	call fn00000000004015C0 (retsize: 8;)
	ecx = Mem0[0x0000000000409008 + 0x00:word32]
	Mem0[0x000000000040900C + 0x00:word32] = eax
	SZO = cond(ecx & ecx)
	C = false
	branch Test(EQ,Z) l000000000040149E
	goto l00000000004013DB
l0000000000401387:
	Mem0[rax + 0x00:word64] = 0x00
	Mem0[0x0000000000409018 + 0x00:word64] = rbp
	call fn0000000000401F50 (retsize: 8;)
	rax = Mem0[0x00000000004062F0 + 0x00:word64]
	rdx = Mem0[0x0000000000409010 + 0x00:word64]
	ecx = Mem0[0x0000000000409020 + 0x00:word32]
	rax = Mem0[rax + 0x00:word64]
	Mem0[rax + 0x00:word64] = rdx
	r8 = Mem0[0x0000000000409010 + 0x00:word64]
	rdx = Mem0[0x0000000000409018 + 0x00:word64]
	call fn00000000004015C0 (retsize: 8;)
	ecx = Mem0[0x0000000000409008 + 0x00:word32]
	Mem0[0x000000000040900C + 0x00:word32] = eax
	SZO = cond(ecx & ecx)
	C = false
	branch Test(EQ,Z) l000000000040149E
	goto l00000000004013DB
l0000000000401387:
	Mem0[rax + 0x00:word64] = 0x00
	Mem0[0x0000000000409018 + 0x00:word64] = rbp
	call fn0000000000401F50 (retsize: 8;)
	rax = Mem0[0x00000000004062F0 + 0x00:word64]
	rdx = Mem0[0x0000000000409010 + 0x00:word64]
	ecx = Mem0[0x0000000000409020 + 0x00:word32]
	rax = Mem0[rax + 0x00:word64]
	Mem0[rax + 0x00:word64] = rdx
	r8 = Mem0[0x0000000000409010 + 0x00:word64]
	rdx = Mem0[0x0000000000409018 + 0x00:word64]
	call fn00000000004015C0 (retsize: 8;)
	ecx = Mem0[0x0000000000409008 + 0x00:word32]
	Mem0[0x000000000040900C + 0x00:word32] = eax
	SZO = cond(ecx & ecx)
	C = false
	branch Test(EQ,Z) l000000000040149E
	goto l00000000004013DB
l00000000004013DB:
	edx = Mem0[0x0000000000409004 + 0x00:word32]
	SZO = cond(edx & edx)
	C = false
	branch Test(NE,Z) l00000000004013F0
	goto l00000000004013E5
l00000000004013DB:
	edx = Mem0[0x0000000000409004 + 0x00:word32]
	SZO = cond(edx & edx)
	C = false
	branch Test(NE,Z) l00000000004013F0
	goto l00000000004013E5
l00000000004013DB:
	edx = Mem0[0x0000000000409004 + 0x00:word32]
	SZO = cond(edx & edx)
	C = false
	branch Test(NE,Z) l00000000004013F0
	goto l00000000004013E5
l00000000004013E5:
	call _cexit (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	eax = Mem0[0x000000000040900C + 0x00:word32]
	goto l00000000004013F0
l00000000004013E5:
	call _cexit (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	eax = Mem0[0x000000000040900C + 0x00:word32]
	goto l00000000004013F0
l00000000004013E5:
	call _cexit (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	eax = Mem0[0x000000000040900C + 0x00:word32]
	goto l00000000004013F0
l00000000004013F0:
	rsp = rsp + 0x0098
	SCZO = cond(rsp)
	rbx = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rsi = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rdi = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rbp = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rsp = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rbp = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	return
l00000000004013F0:
	rsp = rsp + 0x0098
	SCZO = cond(rsp)
	rbx = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rsi = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rdi = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rbp = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rsp = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rbp = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	return
l00000000004013F0:
	rsp = rsp + 0x0098
	SCZO = cond(rsp)
	rbx = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rsi = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rdi = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rbp = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rsp = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	rbp = Mem0[rsp + 0x00:word64]
	rsp = rsp + 0x08
	return
l0000000000401400:
	eax = (word32) Mem0[rsp + 0x60:word16]
	goto l000000000040130F
l0000000000401400:
	eax = (word32) Mem0[rsp + 0x60:word16]
	goto l000000000040130F
l0000000000401400:
	eax = (word32) Mem0[rsp + 0x60:word16]
	goto l000000000040130F
l0000000000401410:
	rsi = Mem0[0x0000000000406340 + 0x00:word64]
	ebp = 0x01
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(NE,Z) l0000000000401205
	goto l0000000000401427
l0000000000401410:
	rsi = Mem0[0x0000000000406340 + 0x00:word64]
	ebp = 0x01
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(NE,Z) l0000000000401205
	goto l0000000000401427
l0000000000401410:
	rsi = Mem0[0x0000000000406340 + 0x00:word64]
	ebp = 0x01
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(NE,Z) l0000000000401205
	goto l0000000000401427
l0000000000401427:
	ecx = 0x1F
	call _amsg_exit (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(NE,Z) l0000000000401224
	ecx = 0x1F
	call _amsg_exit (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(NE,Z) l0000000000401224
	goto l000000000040143C
l0000000000401427:
	ecx = 0x1F
	call _amsg_exit (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(NE,Z) l0000000000401224
	ecx = 0x1F
	call _amsg_exit (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(NE,Z) l0000000000401224
	goto l000000000040143C
l0000000000401427:
	ecx = 0x1F
	call _amsg_exit (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(NE,Z) l0000000000401224
	ecx = 0x1F
	call _amsg_exit (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	eax = Mem0[rsi + 0x00:word32]
	SCZO = cond(eax - 0x01)
	branch Test(NE,Z) l0000000000401224
	goto l000000000040143C
l000000000040143C:
	rdx = Mem0[0x0000000000406360 + 0x00:word64]
	rcx = Mem0[0x0000000000406350 + 0x00:word64]
	call _initterm (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	SZO = cond(ebp & ebp)
	C = false
	Mem0[rsi + 0x00:word32] = 0x02
	branch Test(NE,Z) l000000000040122C
	rdx = Mem0[0x0000000000406360 + 0x00:word64]
	rcx = Mem0[0x0000000000406350 + 0x00:word64]
	call _initterm (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	SZO = cond(ebp & ebp)
	C = false
	Mem0[rsi + 0x00:word32] = 0x02
	branch Test(NE,Z) l000000000040122C
	goto l000000000040145D
l000000000040143C:
	rdx = Mem0[0x0000000000406360 + 0x00:word64]
	rcx = Mem0[0x0000000000406350 + 0x00:word64]
	call _initterm (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	SZO = cond(ebp & ebp)
	C = false
	Mem0[rsi + 0x00:word32] = 0x02
	branch Test(NE,Z) l000000000040122C
	rdx = Mem0[0x0000000000406360 + 0x00:word64]
	rcx = Mem0[0x0000000000406350 + 0x00:word64]
	call _initterm (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	SZO = cond(ebp & ebp)
	C = false
	Mem0[rsi + 0x00:word32] = 0x02
	branch Test(NE,Z) l000000000040122C
	goto l000000000040145D
l000000000040143C:
	rdx = Mem0[0x0000000000406360 + 0x00:word64]
	rcx = Mem0[0x0000000000406350 + 0x00:word64]
	call _initterm (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	SZO = cond(ebp & ebp)
	C = false
	Mem0[rsi + 0x00:word32] = 0x02
	branch Test(NE,Z) l000000000040122C
	rdx = Mem0[0x0000000000406360 + 0x00:word64]
	rcx = Mem0[0x0000000000406350 + 0x00:word64]
	call _initterm (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	SZO = cond(ebp & ebp)
	C = false
	Mem0[rsi + 0x00:word32] = 0x02
	branch Test(NE,Z) l000000000040122C
	goto l000000000040145D
l000000000040145D:
	v24 = Mem0[rbx + 0x00:word64]
	Mem0[rbx + 0x00:word64] = rax
	rax = v24
	eax = 0x00
	SZO = cond(0x00)
	C = false
	v25 = Mem0[rbx + 0x00:word64]
	Mem0[rbx + 0x00:word64] = rax
	rax = v25
	goto l000000000040122C
l000000000040145D:
	v38 = Mem0[rbx + 0x00:word64]
	Mem0[rbx + 0x00:word64] = rax
	rax = v38
	eax = 0x00
	SZO = cond(0x00)
	C = false
	v39 = Mem0[rbx + 0x00:word64]
	Mem0[rbx + 0x00:word64] = rax
	rax = v39
	goto l000000000040122C
l000000000040145D:
	eax = 0x00
	v40 = Mem0[rbx + 0x00:word64]
	Mem0[rbx + 0x00:word64] = rax
	rax = v40
	eax = 0x00
	SZO = cond(0x00)
	C = false
	v41 = Mem0[rbx + 0x00:word64]
	Mem0[rbx + 0x00:word64] = rax
	rax = v41
	goto l000000000040122C
l0000000000401470:
	rcx = fp - 0x90
	GetStartupInfoA(tLocB0)
	rsp = fp - 0xA8
	goto l00000000004011B4
l0000000000401470:
	rcx = fp - 0x90
	GetStartupInfoA(tLocB0)
	rsp = fp - 0xA8
	goto l00000000004011B4
l0000000000401470:
	rcx = fp - 0x90
	GetStartupInfoA(tLocB0)
	rsp = fp - 0xA8
	goto l00000000004011B4
l0000000000401480:
	rdx = Mem0[0x0000000000406380 + 0x00:word64]
	Mem0[rsi + 0x00:word32] = 0x01
	rcx = Mem0[0x0000000000406370 + 0x00:word64]
	call _initterm (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	goto l0000000000401219
l0000000000401480:
	rdx = Mem0[0x0000000000406380 + 0x00:word64]
	Mem0[rsi + 0x00:word32] = 0x01
	rcx = Mem0[0x0000000000406370 + 0x00:word64]
	call _initterm (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	goto l0000000000401219
l0000000000401480:
	rdx = Mem0[0x0000000000406380 + 0x00:word64]
	Mem0[rsi + 0x00:word32] = 0x01
	rcx = Mem0[0x0000000000406370 + 0x00:word64]
	call _initterm (retsize: 8; depth: 8)
	rsp = rsp + ~0x07
	goto l0000000000401219
l000000000040149E:
	ecx = 0x00
	exit(Mem0[rsp + 0x00:int32])
	rsp = rsp - 0x28
	SCZO = cond(rsp)
	rax = Mem0[0x00000000004063E0 + 0x00:word64]
	Mem0[rax + 0x00:word32] = 0x01
	call fn0000000000401F90 (retsize: 8; depth: 8)
	call fn0000000000401180 (retsize: 8; depth: 8)
	rsp = rsp + 0x28
	SCZO = cond(rsp)
	return
l000000000040149E:
	ecx = 0x00
	exit(Mem0[rsp + 0x00:int32])
	rsp = rsp - 0x28
	SCZO = cond(rsp)
	rax = Mem0[0x00000000004063E0 + 0x00:word64]
	Mem0[rax + 0x00:word32] = 0x01
	call fn0000000000401F90 (retsize: 8; depth: 8)
	call fn0000000000401180 (retsize: 8; depth: 8)
	rsp = rsp + 0x28
	SCZO = cond(rsp)
	return
l000000000040149E:
	ecx = 0x00
	exit(Mem0[rsp + 0x00:int32])
	rsp = rsp - 0x28
	SCZO = cond(rsp)
	rax = Mem0[0x00000000004063E0 + 0x00:word64]
	Mem0[rax + 0x00:word32] = 0x01
	call fn0000000000401F90 (retsize: 8; depth: 8)
	call fn0000000000401180 (retsize: 8; depth: 8)
	rsp = rsp + 0x28
	SCZO = cond(rsp)
	return
fn0000000000401180_exit:
}

void fn00000000004014E0()
{
	rsp = fp - 0x28;
	SCZO = cond(fp - 0x28);
	rax = Mem0[0x00000000004063E0 + 0x00:word64];
	Mem0[rax + 0x00:word32] = 0x00;
	fn0000000000401F90();
	fn0000000000401180();
	rsp = rsp + 0x28;
	SCZO = cond(rsp);
	return;
}

void fn0000000000401510()
{
	eax = _onexit(tLoc28);
	SZO = cond(rax & rax);
	al = Test(EQ,Z);
	eax = (word32) al;
	eax = -eax;
	rsp = fp;
	SCZO = cond(fp);
	return;
}

void fn0000000000401530()
{
	rsp = fp;
	rcx = 0x0000000000401540;
	fn0000000000401510();
	return;
}

void fn0000000000401550()
{
	dwLoc04 = rbp;
	rsp = fp - 0x0174;
	SCZO = cond(fp - 0x0174);
	rbp = fp - 244;
	dwLoc84 = 0x34;
	dwLoc7C = 0x01;
	dwLoc80 = 0x00;
	dwLoc78 = 0x01;
	rcx = 0x0000000000405000;
	msvcrt.dll!puts();
	fn0000000000401E30();
	eax = 0x01;
	edx = 0x01;
	rcx = 0x0000000000405020;
	msvcrt.dll!printf();
	rcx = 0x0000000000405090;
	msvcrt.dll!puts();
	rsp = rsp + 0x0170;
	SCZO = cond(rsp);
	rbp = Mem0[rsp + 0x00:word64];
	rsp = rsp + 0x08;
	return;
}

void fn00000000004015C0()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x34;
	SCZO = cond(fp - 0x34);
	dwArg0C = ecx;
	qwArg14 = rdx;
	fn0000000000401F50();
	dwLoc08 = 0x00;
	dwLoc0C = 0x00;
	dwLoc10 = 0x00;
	do
	{
		fn00000000004016A0();
		do
		{
			rax = rbp - 0x0C;
			rdx = rax;
			rcx = 0x00000000004050D0;
			msvcrt.dll!scanf();
			eax = Mem0[rbp - 0x0C + 0x00:word32];
			SCZO = cond(eax - 0x02);
			if (Test(NE,Z))
			{
				SCZO = cond(eax - 0x03);
				if (Test(NE,Z))
				{
					SCZO = cond(eax - 0x01);
					if (Test(EQ,Z))
					{
						fn0000000000401740();
						rax = rbp - 0x08;
						rdx = rax;
						rcx = 0x00000000004050D0;
						msvcrt.dll!scanf();
					}
					else
					{
						rcx = 0x00000000004050D8;
						msvcrt.dll!printf();
					}
				}
				else
					fn0000000000401550();
			}
			else
			{
				fn0000000000401DA0();
				rax = rbp - 0x04;
				rdx = rax;
				rcx = 0x00000000004050D0;
				msvcrt.dll!scanf();
			}
			eax = Mem0[rbp - 0x04 + 0x00:word32];
			SZO = cond(eax & eax);
			C = false;
		} while (Test(NE,Z));
		rcx = 0x0000000000405120;
		msvcrt.dll!printf();
		rax = rbp - 0x08;
		rdx = rax;
		rcx = 0x00000000004050D0;
		msvcrt.dll!scanf();
		eax = Mem0[rbp - 0x08 + 0x00:word32];
		SCZO = cond(eax - 0x01);
	} while (Test(NE,Z));
	eax = 0x00;
	rsp = rsp + 0x30;
	SCZO = cond(rsp);
	rbp = Mem0[rsp + 0x00:word64];
	rsp = rsp + 0x08;
	return;
}

void fn00000000004016A0()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x24;
	SCZO = cond(fp - 0x24);
	rcx = 0x0000000000405150;
	msvcrt.dll!puts();
	rcx = 0x000000000040516C;
	msvcrt.dll!puts();
	rcx = 0x0000000000405182;
	msvcrt.dll!puts();
	rcx = 0x0000000000405199;
	msvcrt.dll!puts();
	SCZO = cond(fp - 0x04);
	rbp = qwLoc04;
	rsp = fp + 0x04;
	return;
}

void fn00000000004016E0()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x24;
	SCZO = cond(fp - 0x24);
	rcx = 0x00000000004051B0;
	msvcrt.dll!puts();
	rcx = 0x00000000004051CC;
	msvcrt.dll!puts();
	rcx = 0x00000000004051E8;
	msvcrt.dll!puts();
	rcx = 0x00000000004051FB;
	msvcrt.dll!puts();
	rcx = 0x0000000000405206;
	msvcrt.dll!puts();
	rcx = 0x0000000000405211;
	msvcrt.dll!puts();
	SCZO = cond(fp - 0x04);
	rbp = qwLoc04;
	rsp = fp + 0x04;
	return;
}

void fn0000000000401740()
{
	dwLoc04 = rbp;
	rsp = fp - 884;
	SCZO = cond(fp - 884);
	rbp = fp - 0x02F4;
	fn00000000004016E0();
	dwLoc0348 = 0x00;
	dwLoc08 = 0x00;
	rax = fp - 0x0348;
	rdx = fp - 0x0348;
	rcx = 0x0000000000405220;
	msvcrt.dll!scanf();
	eax = 0x00;
	SCZO = cond(~0x01);
}

void fn00000000004017E0()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x34;
	SCZO = cond(fp - 0x34);
	rcx = 0x00000000004052D0;
	msvcrt.dll!puts();
	rax = 0x0000000000409980;
	rdx = rax;
	rcx = 0x0000000000405317;
	msvcrt.dll!scanf();
	rcx = 0x0000000000405320;
	msvcrt.dll!puts();
	rax = 0x0000000000409980;
	rdx = rax + 100;
	rcx = 0x0000000000405317;
	msvcrt.dll!scanf();
	qwLoc0C = 0x00;
	rdx = 0x000000000040534B;
	rcx = 0x0000000000405350;
	msvcrt.dll!fopen();
	qwLoc0C = rax;
	rcx = qwLoc0C;
	rax = 0x0000000000409980;
	r9 = rax;
	rax = 0x0000000000409980;
	r8 = r8 + 100;
	rdx = 0x0000000000405370;
	msvcrt.dll!fprintf();
	rax = qwLoc0C;
	rcx = qwLoc0C;
	msvcrt.dll!fclose();
	r8 = r8 + 100;
	rax = 0x0000000000409980;
	rdx = rax;
	rcx = 0x0000000000405508;
	msvcrt.dll!printf();
	rcx = 0x0000000000405568;
	msvcrt.dll!puts();
	rcx = 0x00000000004055D3;
	msvcrt.dll!printf();
	SCZO = cond(fp - 0x04);
	rbp = qwLoc04;
	rsp = fp + 0x04;
	return;
}

void fn00000000004018BD()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x34;
	SCZO = cond(fp - 0x34);
	rcx = 0x00000000004052D0;
	msvcrt.dll!puts();
	rax = 0x0000000000409C20;
	rdx = rax;
	rcx = 0x0000000000405317;
	msvcrt.dll!scanf();
	rcx = 0x0000000000405320;
	msvcrt.dll!puts();
	rax = 0x0000000000409C20;
	rdx = rax + 100;
	rcx = 0x0000000000405317;
	msvcrt.dll!scanf();
	qwLoc0C = 0x00;
	rdx = 0x000000000040534B;
	rcx = 0x00000000004055F8;
	msvcrt.dll!fopen();
	qwLoc0C = rax;
	rcx = qwLoc0C;
	rax = 0x0000000000409C20;
	r9 = rax;
	rax = 0x0000000000409C20;
	r8 = r8 + 100;
	rdx = 0x0000000000405370;
	msvcrt.dll!fprintf();
	rax = qwLoc0C;
	rcx = qwLoc0C;
	msvcrt.dll!fclose();
	r8 = r8 + 100;
	rax = 0x0000000000409C20;
	rdx = rax;
	rcx = 0x0000000000405620;
	msvcrt.dll!printf();
	rcx = 0x0000000000405680;
	msvcrt.dll!printf();
	rcx = 0x00000000004055D3;
	msvcrt.dll!printf();
	SCZO = cond(fp - 0x04);
	rbp = qwLoc04;
	rsp = fp + 0x04;
	return;
}

void fn000000000040199A()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x34;
	SCZO = cond(fp - 0x34);
	rcx = 0x00000000004052D0;
	msvcrt.dll!puts();
	rax = 0x0000000000409B40;
	rdx = rax;
	rcx = 0x0000000000405317;
	msvcrt.dll!scanf();
	rcx = 0x0000000000405320;
	msvcrt.dll!puts();
	rax = 0x0000000000409B40;
	rdx = rax + 100;
	rcx = 0x0000000000405317;
	msvcrt.dll!scanf();
	qwLoc0C = 0x00;
	rdx = 0x000000000040534B;
	rcx = 0x00000000004056F0;
	msvcrt.dll!fopen();
	qwLoc0C = rax;
	rcx = qwLoc0C;
	rax = 0x0000000000409B40;
	r9 = rax;
	rax = 0x0000000000409B40;
	r8 = r8 + 100;
	rdx = 0x0000000000405718;
	msvcrt.dll!fprintf();
	rax = qwLoc0C;
	rcx = qwLoc0C;
	msvcrt.dll!fclose();
	r8 = r8 + 100;
	rax = 0x0000000000409B40;
	rdx = rax;
	rcx = 0x00000000004058D0;
	msvcrt.dll!printf();
	rcx = 0x0000000000405680;
	msvcrt.dll!printf();
	rcx = 0x000000000040592E;
	msvcrt.dll!printf();
	SCZO = cond(fp - 0x04);
	rbp = qwLoc04;
	rsp = fp + 0x04;
	return;
}

void fn0000000000401A77()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x34;
	SCZO = cond(fp - 0x34);
	rcx = 0x0000000000405320;
	msvcrt.dll!puts();
	rax = 0x0000000000409A60;
	rdx = rax + 100;
	rcx = 0x0000000000405317;
	msvcrt.dll!scanf();
	qwLoc0C = 0x00;
	rdx = 0x000000000040534B;
	rcx = 0x0000000000405950;
	msvcrt.dll!fopen();
	qwLoc0C = rax;
	rcx = qwLoc0C;
	rax = 0x0000000000409A60;
	r8 = r8 + 100;
	rdx = 0x0000000000405988;
	msvcrt.dll!fprintf();
	rax = qwLoc0C;
	rcx = qwLoc0C;
	msvcrt.dll!fclose();
	r8 = r8 + 100;
	rax = 0x0000000000409A60;
	rdx = rax;
	rcx = 0x00000000004059D0;
	msvcrt.dll!printf();
	rcx = 0x0000000000405568;
	msvcrt.dll!puts();
	rcx = 0x0000000000405A2D;
	msvcrt.dll!printf();
	SCZO = cond(fp - 0x04);
	rbp = qwLoc04;
	rsp = fp + 0x04;
	return;
}

void fn0000000000401B30()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x24;
	SCZO = cond(fp - 0x24);
	rcx = 0x0000000000405A50;
	msvcrt.dll!puts();
	rcx = 0x0000000000405A74;
	msvcrt.dll!puts();
	rcx = 0x0000000000405A7E;
	msvcrt.dll!puts();
	rcx = 0x0000000000405A89;
	msvcrt.dll!puts();
	SCZO = cond(fp - 0x04);
	rbp = qwLoc04;
	rsp = fp + 0x04;
	return;
}

void fn0000000000401B6F()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x34;
	SCZO = cond(fp - 0x34);
	dwLoc08 = 0x00;
	fn0000000000401B30();
	rax = fp - 0x08;
	rdx = fp - 0x08;
	rcx = 0x0000000000405A94;
	msvcrt.dll!scanf();
	eax = 0x00;
	SCZO = cond(~0x01);
	if (Test(NE,Z))
	{
		SCZO = cond(~0x02);
		if (Test(NE,Z))
		{
			SCZO = cond(~0x00);
			if (Test(EQ,Z))
			{
				rcx = 0x0000000000405A98;
				msvcrt.dll!printf();
				fn00000000004017E0();
			}
			else
			{
				rcx = 0x0000000000405B40;
				msvcrt.dll!printf();
				rcx = 0x0000000000405B70;
				msvcrt.dll!printf();
			}
		}
		else
		{
			rcx = 0x0000000000405B08;
			msvcrt.dll!printf();
			fn00000000004017E0();
		}
	}
	else
	{
		rcx = 0x0000000000405AD0;
		msvcrt.dll!printf();
		fn00000000004017E0();
	}
	rsp = rsp + 0x30;
	SCZO = cond(rsp);
	rbp = Mem0[rsp + 0x00:word64];
	rsp = rsp + 0x08;
	return;
}

void fn0000000000401C01()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x34;
	SCZO = cond(fp - 0x34);
	dwLoc08 = 0x00;
	fn0000000000401B30();
	rax = fp - 0x08;
	rdx = fp - 0x08;
	rcx = 0x0000000000405A94;
	msvcrt.dll!scanf();
	eax = 0x00;
	SCZO = cond(~0x01);
	if (Test(NE,Z))
	{
		SCZO = cond(~0x02);
		if (Test(NE,Z))
		{
			SCZO = cond(~0x00);
			if (Test(EQ,Z))
			{
				rcx = 0x0000000000405A98;
				msvcrt.dll!printf();
				fn00000000004018BD();
			}
			else
			{
				rcx = 0x0000000000405B40;
				msvcrt.dll!printf();
			}
		}
		else
		{
			rcx = 0x0000000000405B08;
			msvcrt.dll!printf();
			fn00000000004018BD();
		}
	}
	else
	{
		rcx = 0x0000000000405AD0;
		msvcrt.dll!printf();
		fn00000000004018BD();
	}
	rsp = rsp + 0x30;
	SCZO = cond(rsp);
	rbp = Mem0[rsp + 0x00:word64];
	rsp = rsp + 0x08;
	return;
}

void fn0000000000401C87()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x34;
	SCZO = cond(fp - 0x34);
	dwLoc08 = 0x00;
	fn0000000000401B30();
	rax = fp - 0x08;
	rdx = fp - 0x08;
	rcx = 0x0000000000405A94;
	msvcrt.dll!scanf();
	eax = 0x00;
	SCZO = cond(~0x01);
	if (Test(NE,Z))
	{
		SCZO = cond(~0x02);
		if (Test(NE,Z))
		{
			SCZO = cond(~0x00);
			if (Test(EQ,Z))
			{
				rcx = 0x0000000000405A98;
				msvcrt.dll!printf();
				fn000000000040199A();
			}
			else
			{
				rcx = 0x0000000000405B40;
				msvcrt.dll!printf();
			}
		}
		else
		{
			rcx = 0x0000000000405B08;
			msvcrt.dll!printf();
			fn000000000040199A();
		}
	}
	else
	{
		rcx = 0x0000000000405AD0;
		msvcrt.dll!printf();
		fn000000000040199A();
	}
	rsp = rsp + 0x30;
	SCZO = cond(rsp);
	rbp = Mem0[rsp + 0x00:word64];
	rsp = rsp + 0x08;
	return;
}

void fn0000000000401D0D()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x34;
	SCZO = cond(fp - 0x34);
	dwLoc08 = 0x00;
	fn0000000000401B30();
	rax = fp - 0x08;
	rdx = fp - 0x08;
	rcx = 0x0000000000405A94;
	msvcrt.dll!scanf();
	eax = 0x00;
	SCZO = cond(~0x01);
	if (Test(NE,Z))
	{
		SCZO = cond(~0x02);
		if (Test(NE,Z))
		{
			SCZO = cond(~0x00);
			if (Test(EQ,Z))
			{
				rcx = 0x0000000000405A98;
				msvcrt.dll!printf();
				fn0000000000401A77();
			}
			else
			{
				rcx = 0x0000000000405B40;
				msvcrt.dll!printf();
			}
		}
		else
		{
			rcx = 0x0000000000405B08;
			msvcrt.dll!printf();
			fn0000000000401A77();
		}
	}
	else
	{
		rcx = 0x0000000000405AD0;
		msvcrt.dll!printf();
		fn0000000000401A77();
	}
	rsp = rsp + 0x30;
	SCZO = cond(rsp);
	rbp = Mem0[rsp + 0x00:word64];
	rsp = rsp + 0x08;
	return;
}

void fn0000000000401DA0()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x24;
	SCZO = cond(fp - 0x24);
	rcx = 0x0000000000405BA0;
	msvcrt.dll!puts();
	rcx = 0x0000000000405BC8;
	msvcrt.dll!puts();
	rcx = 0x0000000000405BFA;
	msvcrt.dll!puts();
	rcx = 0x0000000000405C18;
	msvcrt.dll!puts();
	rcx = 0x0000000000405C60;
	msvcrt.dll!puts();
	rcx = 0x0000000000405CC0;
	msvcrt.dll!puts();
	rcx = 0x0000000000405D00;
	msvcrt.dll!puts();
	rcx = 0x0000000000405D68;
	msvcrt.dll!puts();
	rcx = 0x0000000000405DC0;
	msvcrt.dll!puts();
	rcx = 0x0000000000405E10;
	msvcrt.dll!puts();
	SCZO = cond(fp - 0x04);
	rbp = qwLoc04;
	rsp = fp + 0x04;
	return;
}

void fn0000000000401E30()
{
	dwLoc04 = rbp;
	rbp = fp - 0x04;
	rsp = fp - 0x24;
	SCZO = cond(fp - 0x24);
	rcx = 0x0000000000405E40;
	msvcrt.dll!puts();
	rcx = 0x0000000000405E98;
	msvcrt.dll!puts();
	rcx = 0x0000000000405ED8;
	msvcrt.dll!printf();
	rcx = 0x0000000000405EF8;
	msvcrt.dll!printf();
	rcx = 0x0000000000405F20;
	msvcrt.dll!printf();
	rcx = 0x0000000000405F50;
	msvcrt.dll!printf();
	rcx = 0x0000000000405F88;
	msvcrt.dll!puts();
	SCZO = cond(fp - 0x04);
	rbp = qwLoc04;
	rsp = fp + 0x04;
	return;
}

void fn0000000000401F50()
{
	rsp = fp;
	eax = Mem0[0x0000000000409030 + 0x00:word32];
	SZO = cond(eax & eax);
	C = false;
}

void fn0000000000401F90()
{
	rsp = fp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rdi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbx;
	rsp = rsp - 0x30;
	rbx = Mem0[0x00000000004040B0 + 0x00:word64];
	r8 = 769630770;
	SCZO = cond(rbx - rax);
	Mem0[rsp + 0x20:word64] = 0x00;
}

void fn0000000000402390()
{
	rsp = fp;
}

void fn00000000004023C0()
{
	rsp = fp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rdi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbx;
	rsp = rsp - 0x50;
	rsi = (int64) Mem0[0x0000000000409624 + 0x00:word32];
	SZO = cond(esi & esi);
	C = false;
	rbx = rcx;
	rbp = rdx;
	rdi = r8;
}

void fn0000000000402590()
{
	rsp = fp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rdi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rdi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbx;
	rsp = rsp - 0x38;
	rbp = rsp + 0x80;
	ebx = Mem0[0x0000000000409620 + 0x00:word32];
	SZO = cond(ebx & ebx);
	C = false;
}

void fn00000000004029F0()
{
	rsp = fp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rdi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbx;
	rsp = rsp - 0x20;
	SCZO = cond(rsp);
	fn0000000000403190();
	rbp = rax;
	eax = Mem0[0x0000000000409648 + 0x00:word32];
	SZO = cond(eax & eax);
	C = false;
}

void fn0000000000402F40()
{
	rsp = fp;
	rax = (int64) Mem0[rcx + 0x3C:word32];
	rcx = rcx + rax;
	eax = eax ^ eax;
	SCZO = cond(Mem0[rcx + 0x00:word32] - 0x4550);
}

void fn0000000000402FD0()
{
	rsp = fp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rdi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbx;
	rsp = rsp - 0x20;
	rsi = rcx;
	eax = strlen(Mem0[rsp + 0x00:(ptr char)]);
	SCZO = cond(rax - 0x08);
}

void fn0000000000403060()
{
	rsp = fp;
	rsp = rsp - 0x28;
	r8 = Mem0[0x00000000004062E0 + 0x00:word64];
	SCZO = cond(Mem0[rax + 0x00:word16] - 23117);
	rdx = rcx;
}

void fn00000000004030E0()
{
	rsp = fp;
	rsp = rsp - 0x28;
	rdx = Mem0[0x00000000004062E0 + 0x00:word64];
	r8d = r8d ^ r8d;
	SCZO = cond(Mem0[rdx + 0x00:word16] - 23117);
}

void fn0000000000403120()
{
	rsp = fp;
	rsp = rsp - 0x28;
	r8 = Mem0[0x00000000004062E0 + 0x00:word64];
	SCZO = cond(Mem0[rax + 0x00:word16] - 23117);
	rdx = rcx;
}

void fn0000000000403190()
{
	rsp = fp;
	rsp = rsp - 0x28;
	rdx = Mem0[0x00000000004062E0 + 0x00:word64];
	SCZO = cond(Mem0[rdx + 0x00:word16] - 23117);
}

void fn0000000000403320()
{
	rsp = fp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rcx;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rax;
	SCZO = cond(r8 - 0x1000);
	rcx = rsp + 0x18;
	if (Test(UGE,C))
		do
		{
			rcx = rcx - 0x00001000;
			v8 = Mem0[rcx + 0x00:word64] | 0x00;
			Mem0[rcx + 0x00:word64] = v8;
			SZO = cond(Mem0[rcx + 0x00:word64]);
			r8 = r8 - 0x00001000;
			SCZO = cond(r8 - 0x1000);
		} while (Test(UGT,CZ));
	rcx = rcx - rax;
	v11 = Mem0[rcx + 0x00:word64] | 0x00;
	Mem0[rcx + 0x00:word64] = v11;
	SZO = cond(Mem0[rcx + 0x00:word64]);
	C = false;
	rax = Mem0[rsp + 0x00:word64];
	rsp = rsp + 0x08;
	rcx = Mem0[rsp + 0x00:word64];
	rsp = rsp + 0x08;
	return;
}

void fn0000000000403430()
{
	rsp = fp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbx;
	rsp = rsp - 0x20;
	SCZO = cond(rsp);
	ebx = ecx;
	__iob_func();
	rsp = rsp + ~0x07;
	ecx = ebx;
	rdx = rcx + rcx * 0x02;
	rdx = rdx << 0x04;
	rax = rax + rdx;
	rsp = rsp + 0x20;
	SCZO = cond(rsp);
	rbx = Mem0[rsp + 0x00:word64];
	rsp = rsp + 0x08;
	return;
}

void fn0000000000403460()
{
	rsp = fp;
	rax = rcx;
	v5 = Mem0[0x0000000000409950 + 0x00:word64];
	Mem0[0x0000000000409950 + 0x00:word64] = rax;
	rax = v5;
	return;
}

void fn0000000000403470()
{
	rsp = fp;
	rax = Mem0[0x0000000000406300 + 0x00:word64];
	rax = Mem0[rax + 0x00:word64];
	return;
}

void fn0000000000403560()
{
	rsp = fp;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rsi;
	rsp = rsp - 0x04;
	Mem0[rsp + 0x00:word32] = rbx;
	rsp = rsp - 0x38;
	SCZO = cond(rsp);
	rax = rsp + 88;
	rbx = rcx;
	ecx = 0x02;
	Mem0[rsp + 88:word64] = rdx;
	Mem0[rsp + 0x60:word64] = r8;
	Mem0[rsp + 0x68:word64] = r9;
	Mem0[rsp + 0x28:word64] = rax;
	fn0000000000403430();
	eax = 0x1B;
	edx = 0x01;
	rcx = 0x0000000000406160;
	r9 = rax;
	msvcrt.dll!fwrite();
	rsi = Mem0[rsp + 0x28:word64];
	ecx = 0x02;
	fn0000000000403430();
	rdx = rbx;
	rcx = rax;
	r8 = rsi;
	msvcrt.dll!vfprintf();
	abort();
	fn0000000000401530();
	return;
}

